const LOGIN = "LOGIN";
const REGISTER = "REGISTER";
const EMAIL_ACTIVE_CODE = "EMAIL_ACTIVE_CODE";
const PHONE_ACTIVE_CODE = "PHONE_ACTIVE_CODE";
const FORGOT_PASSWORD = "FORGOT_PASSWORD";
const REGISTER_OTP = "REGISTER_OTP";
const FORGOT_OTP = "FORGOT_OTP";
const CREATE_PASSWORD = "CREATE_PASSWORD";
const RESET_PASSWORD = "RESET_PASSWORD";

export const AUTH_STEP = {
  [LOGIN]: LOGIN,
  [EMAIL_ACTIVE_CODE]: EMAIL_ACTIVE_CODE,
  [PHONE_ACTIVE_CODE]: PHONE_ACTIVE_CODE,
  [REGISTER]: REGISTER,
  [FORGOT_PASSWORD]: FORGOT_PASSWORD,
  [REGISTER_OTP]: REGISTER_OTP,
  [FORGOT_OTP]: FORGOT_OTP,
  [CREATE_PASSWORD]: CREATE_PASSWORD,
  [RESET_PASSWORD]: RESET_PASSWORD,
};

export const STEP_TITLE = {
  [LOGIN]: null,
  [REGISTER]: "",
  [EMAIL_ACTIVE_CODE]: "Mã xác minh",
  [PHONE_ACTIVE_CODE]: "Mã xác minh",
  [FORGOT_PASSWORD]: "Quên mật khẩu",
  [REGISTER_OTP]: "Mã xác minh",
  [FORGOT_OTP]: "Mã xác minh",
  [CREATE_PASSWORD]: "Tạo mật khẩu mới",
  [RESET_PASSWORD]: "Reset mật khẩu",
};

export const ACCESS_TOKEN = "ACCESS_TOKEN";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
